// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cn_compile
SEXP cn_compile(Rcpp::DataFrame edges, Rcpp::CharacterVector node_names, Rcpp::NumericVector initial_values, double dt, int horizon, double epsilon, int baseline_max_steps);
RcppExport SEXP _cellnetR_cn_compile(SEXP edgesSEXP, SEXP node_namesSEXP, SEXP initial_valuesSEXP, SEXP dtSEXP, SEXP horizonSEXP, SEXP epsilonSEXP, SEXP baseline_max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type node_names(node_namesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type baseline_max_steps(baseline_max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(cn_compile(edges, node_names, initial_values, dt, horizon, epsilon, baseline_max_steps));
    return rcpp_result_gen;
END_RCPP
}
// cn_perturb
Rcpp::DataFrame cn_perturb(SEXP pointer, std::string target, double effect, std::string strategy);
RcppExport SEXP _cellnetR_cn_perturb(SEXP pointerSEXP, SEXP targetSEXP, SEXP effectSEXP, SEXP strategySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< std::string >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type effect(effectSEXP);
    Rcpp::traits::input_parameter< std::string >::type strategy(strategySEXP);
    rcpp_result_gen = Rcpp::wrap(cn_perturb(pointer, target, effect, strategy));
    return rcpp_result_gen;
END_RCPP
}
// cn_perturb_reaction
Rcpp::DataFrame cn_perturb_reaction(SEXP pointer, int reaction_id, double effect, std::string strategy);
RcppExport SEXP _cellnetR_cn_perturb_reaction(SEXP pointerSEXP, SEXP reaction_idSEXP, SEXP effectSEXP, SEXP strategySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< int >::type reaction_id(reaction_idSEXP);
    Rcpp::traits::input_parameter< double >::type effect(effectSEXP);
    Rcpp::traits::input_parameter< std::string >::type strategy(strategySEXP);
    rcpp_result_gen = Rcpp::wrap(cn_perturb_reaction(pointer, reaction_id, effect, strategy));
    return rcpp_result_gen;
END_RCPP
}
// cn_perturb_batch
Rcpp::List cn_perturb_batch(SEXP pointer, Rcpp::CharacterVector targets, double effect, std::string strategy);
RcppExport SEXP _cellnetR_cn_perturb_batch(SEXP pointerSEXP, SEXP targetsSEXP, SEXP effectSEXP, SEXP strategySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< double >::type effect(effectSEXP);
    Rcpp::traits::input_parameter< std::string >::type strategy(strategySEXP);
    rcpp_result_gen = Rcpp::wrap(cn_perturb_batch(pointer, targets, effect, strategy));
    return rcpp_result_gen;
END_RCPP
}
// cn_set_context
void cn_set_context(SEXP pointer, Rcpp::CharacterVector nodes, Rcpp::NumericVector multipliers);
RcppExport SEXP _cellnetR_cn_set_context(SEXP pointerSEXP, SEXP nodesSEXP, SEXP multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type multipliers(multipliersSEXP);
    cn_set_context(pointer, nodes, multipliers);
    return R_NilValue;
END_RCPP
}
// cn_run_protocol
Rcpp::List cn_run_protocol(SEXP pointer, Rcpp::DataFrame events, double end_time, Rcpp::NumericVector sample_times, std::string strategy);
RcppExport SEXP _cellnetR_cn_run_protocol(SEXP pointerSEXP, SEXP eventsSEXP, SEXP end_timeSEXP, SEXP sample_timesSEXP, SEXP strategySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< double >::type end_time(end_timeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sample_times(sample_timesSEXP);
    Rcpp::traits::input_parameter< std::string >::type strategy(strategySEXP);
    rcpp_result_gen = Rcpp::wrap(cn_run_protocol(pointer, events, end_time, sample_times, strategy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cellnetR_cn_compile", (DL_FUNC) &_cellnetR_cn_compile, 7},
    {"_cellnetR_cn_perturb", (DL_FUNC) &_cellnetR_cn_perturb, 4},
    {"_cellnetR_cn_perturb_reaction", (DL_FUNC) &_cellnetR_cn_perturb_reaction, 4},
    {"_cellnetR_cn_perturb_batch", (DL_FUNC) &_cellnetR_cn_perturb_batch, 4},
    {"_cellnetR_cn_set_context", (DL_FUNC) &_cellnetR_cn_set_context, 3},
    {"_cellnetR_cn_run_protocol", (DL_FUNC) &_cellnetR_cn_run_protocol, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_cellnetR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
