# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cn_compile <- function(edges, node_names, initial_values, dt, horizon, epsilon, baseline_max_steps) {
    .Call(`_cellnetR_cn_compile`, edges, node_names, initial_values, dt, horizon, epsilon, baseline_max_steps)
}

cn_perturb <- function(pointer, target, effect, strategy) {
    .Call(`_cellnetR_cn_perturb`, pointer, target, effect, strategy)
}

cn_perturb_reaction <- function(pointer, reaction_id, effect, strategy) {
    .Call(`_cellnetR_cn_perturb_reaction`, pointer, reaction_id, effect, strategy)
}

cn_perturb_batch <- function(pointer, targets, effect, strategy) {
    .Call(`_cellnetR_cn_perturb_batch`, pointer, targets, effect, strategy)
}

cn_set_context <- function(pointer, nodes, multipliers) {
    invisible(.Call(`_cellnetR_cn_set_context`, pointer, nodes, multipliers))
}

cn_run_protocol <- function(pointer, events, end_time, sample_times, strategy) {
    .Call(`_cellnetR_cn_run_protocol`, pointer, events, end_time, sample_times, strategy)
}

